name: "Betterscan"

on: 
  push:
    branches: [ "master" ]

jobs:
  betterscan:
    runs-on: ubuntu-latest
    name: Betterscan Scan and Report
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Betterscan Scan
        uses: topcodersonline/betterscan@v3
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
